var classes = [
	'English',
	'English I',
	'English II',
	'English III',
	'English IV',
	'Remedial English',
	'Esl – English As Second Language',
	'World Literature',
	'Ancient Literature',
	'Medieval Literature',
	'Renaissance Literature',
	'Modern Literature',
	'British Literature',
	'American Literature',
	'Short Story',
	'Classical Literature',
	'Shakespeare',
	'Heroes, Myth And Legend',
	'Film As Literature',
	'Composition',
	'Creative Writing',
	'Poetry',
	'Grammar',
	'Vocabulary',
	'Debate',
	'Speech',
	'Journalism',
	'Publishing Skills',
	'Photojournalism',
	'Yearbook',
	'Study Skills',
	'Research Skills',
	'Fine Arts',
	'Art I',
	'Art II',
	'Art III',
	'Art IV',
	'Art Appreciation',
	'Art History',
	'Drawing',
	'Painting',
	'Sculpture',
	'Ceramics',
	'Pottery',
	'Instrumental Music',
	'Music Appreciation',
	'Music History',
	'Music Theory',
	'Music Fundamentals',
	'Band',
	'Orchestra',
	'Choir',
	'Voice',
	'Classical Music Studies',
	'Performing Arts',
	'Theatre Arts',
	'Improvisational Theater',
	'Dance',
	'Applied Arts',
	'Computer Aided Design',
	'Digital Media',
	'Photography',
	'Videography',
	'History Of Film',
	'Film Production',
	'Leather Working',
	'Drafting',
	'Metal Work',
	'Small Engine Mechanics',
	'Auto Mechanics',
	'Science',
	'General Science',
	'Physics',
	'Physical Science',
	'Chemistry',
	'Organic Chemistry',
	'Life Science',
	'Biology',
	'Zoology',
	'Marine Biology',
	'Botany',
	'Earth Science',
	'Geology',
	'Oceanography',
	'Meteorology',
	'Astronomy',
	'Animal Science',
	'Equine Science',
	'Veterinary Science',
	'Forensic Science',
	'Ecology',
	'Environmental Science',
	'Gardening',
	'Food Science',
	'Foreign Language',
	'Spanish',
	'French',
	'Japanese',
	'German',
	'Latin',
	'Greek',
	'Hebrew',
	'Chinese',
	'Sign Language',
	'Math',
	'Remedial Math',
	'Fundamental Math Or Basic Math',
	'Mathematics',
	'Pre-algebra',
	'Introduction To Algebra',
	'Algebra',
	'Algebra I',
	'Algebra II',
	'Intermediate Algebra',
	'Geometry',
	'Trigonometry',
	'Precalculus',
	'Calculus',
	'Statistics',
	'Business Math',
	'Consumer Math',
	'Accounting',
	'Personal Finance And Investing',
	'Social Studies',
	'Ancient History',
	'Medieval History',
	'Greek And Roman History',
	'Renaissance History With Us History',
	'Modern History With Us History',
	'World History',
	'World Geography',
	'Us History',
	'World Religions',
	'World Current Events',
	'Government',
	'Civics',
	'Economics',
	'Political Science',
	'Social Sciences',
	'Psychology',
	'Sociology',
	'Anthropology',
	'Genealogy',
	'Philosophy',
	'Logic',
	'Logic I',
	'Logic II',
	'Critical Thinking',
	'Rhetoric',
	'Health',
	'Basic First Aid And Safety',
	'Nutrition',
	'Healthful Living',
	'Gymnastics',
	'Track And Field',
	'Archery',
	'Fencing',
	'Golf',
	'Rock Climbing',
	'Outdoor Survival Skills',
	'Hiking',
	'Equestrian Skills',
	'Weightlifting',
	'Physical Fitness',
	'Aerobics',
	'Yoga',
	'Martial Arts',
	'Ice Skating',
	'Figure Skating',
	'Cycling',
	'Bowling',
	'Adapted P.E',
	'Computers',
	'Keyboarding',
	'Word Processing',
	'Computer Aided Drafting',
	'Computer Applications',
	'Computer Graphics',
	'Digital Arts',
	'Photoshop',
	'Programming',
	'Computer Repair',
	'Web Design',
	'Desktop Publishing',
	'Life Skills',
	'Culinary Arts',
	'Child Development',
	'Home Management',
	'Home Organization',
	'Basic Yard Care',
	'Financial Management',
	'Drivers Education',
	'Personal Organization',
	'Social Skills',
	'Career Planning'
];
