var vegetables = [
  "artichoke",
  "arugula",
  "asparagus",
  "aubergine",
  "eggplant",
  "amaranth",
  "legumes",
  "alfalfa sprouts",
  "azuki beans",
  "bean sprouts",
  "black beans",
  "black-eyed peas",
  "borlotti bean",
  "broad beans",
  "chickpeas",
  "garbanzos",
  "green beans",
  "kidney beans",
  "lentils",
  "lima beans",
  "butter beans",
  "mung beans",
  "navy beans",
  "pinto beans",
  "runner beans",
  "split peas",
  "soy beans",
  "peas",
  "mangetout",
  "snap peas",
  "bok choy",
  "broccoflower",
  "broccoli",
  "brussels sprouts",
  "cabbage",
  "calabrese",
  "carrots",
  "cauliflower",
  "celery",
  "chard",
  "collard greens",
  "corn salad",
  "endive",
  "fiddleheads",
  "frisee",
  "fennel",
  "anise",
  "basil",
  "caraway",
  "coriander",
  "chamomile",
  "dill",
  "fennel",
  "lavender",
  "lemon grass",
  "marjoram",
  "oregano",
  "parsley",
  "rosemary",
  "sage",
  "thyme",
  "kale",
  "kohlrabi",
  "lettuce lactuca sativa",
  "maize",
  "corn",
  "sweetcorn",
  "mushrooms",
  "mustard greens",
  "nettles",
  "new zealand spinach",
  "okra",
  "onion family",
  "chives",
  "garlic",
  "leek allium porrum",
  "onion",
  "shallot",
  "spring onion",
  "green onion",
  "scallion",
  "parsley",
  "peppers",
  "green pepper",
  "red pepper",
  "bell pepper",
  "pimento",
  "chili pepper",
  "jalapeno",
  "habanero",
  "paprika",
  "tabasco pepper",
  "cayenne pepper",
  "radicchio",
  "rhubarb",
  "root vegetables",
  "beetroot",
  "beet",
  "carrot",
  "celeriac",
  "daikon",
  "ginger",
  "parsnip",
  "rutabaga",
  "turnip",
  "radish",
  "swede",
  "rutabaga",
  "turnip",
  "wasabi",
  "horseradish",
  "white radish",
  "salsify",
  "skirret",
  "spinach",
  "topinambur",
  "squashes",
  "acorn squash",
  "butternut squash",
  "banana squash",
  "courgette",
  "zucchini",
  "cucumber",
  "delicata",
  "gem squash",
  "hubbard squash",
  "marrow",
  "squash",
  "patty pans",
  "pumpkin",
  "spaghetti squash",
  "tat soi",
  "tomato",
  "tubers",
  "jicama",
  "jerusalem artichoke",
  "potato",
  "sunchokes",
  "sweet potato",
  "taro",
  "yam",
  "water chestnut",
  "watercress",
  "zucchini"
];
